
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 5;
  public static final int ELSE = 22;
  public static final int PLUS = 3;
  public static final int INT = 17;
  public static final int RPAREN = 8;
  public static final int EQUAL = 16;
  public static final int WHILE = 23;
  public static final int SEMI = 2;
  public static final int RETURN = 15;
  public static final int RKEY = 9;
  public static final int FUNCTION = 11;
  public static final int IF = 21;
  public static final int LPAREN = 7;
  public static final int ID = 26;
  public static final int LKEY = 10;
  public static final int BOOLEAN = 19;
  public static final int STRING = 20;
  public static final int COMA = 14;
  public static final int FLOAT = 18;
  public static final int NUMBER = 25;
  public static final int EOF = 0;
  public static final int DIVIDE = 6;
  public static final int MAIN = 13;
  public static final int MINUS = 4;
  public static final int error = 1;
  public static final int FOR = 24;
  public static final int VOID = 12;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "LPAREN",
  "RPAREN",
  "RKEY",
  "LKEY",
  "FUNCTION",
  "VOID",
  "MAIN",
  "COMA",
  "RETURN",
  "EQUAL",
  "INT",
  "FLOAT",
  "BOOLEAN",
  "STRING",
  "IF",
  "ELSE",
  "WHILE",
  "FOR",
  "NUMBER",
  "ID"
  };
}

